### PR TITLE
Make cocoahelper compatible with macos 10.10 - 10.12

### PR DESCRIPTION
**Pull request by uldza**

### CODE REVIEW

**Comment by elliottslaughter** [comment]
Thanks for the PR!

One thing I'm wondering is if this fix is needed for 10.13 as well. The cocoahelper code was originally written a long time ago, so if something broke in 10.10 it's likely needed in 10.13 too.

**Comment by uldza** [comment]
I'm not expert in OSX, but if I understand correctly NSAlternateKeyMask NSCommandKeyMask where deprecated in 10.12 and NSEventModifierFlagOption NSEventModifierFlagCommand used instead.
I was trying to get lispbuilder working on 10.11.6 and it was failing when making cocoahelper. A little research led to these changes. So in result I created this pull req, since someone else could have similar issue.

**Comment by elliottslaughter** [comment]
Apparently I forgot I was the one who originally changed that. :( This looks good, thanks for spending the time to do this.

**Comment by uldza** [comment]
Thanks

**Pull request merged**
